apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel   # php container with installed laravel app
          image: jusis707/lav:14
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
              memory: 256Mi
          env:    # get environment variables from secrets
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: dbName
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: dbUserNameKey
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: dbPasswordKey
          ports:
            - containerPort: 9000
              name: laravel-9000
            - containerPort: 8000
              name: laravel-8000
          lifecycle:  
            postStart:  # commands that will be executed after container was created
              exec:
                command:  #generate key, 
                  - "sh" 
                  - "-c"
                  - >
                    mkdir /mnt/data;
          volumeMounts:
# mount volume for communication with nginx
            - name: shared-files
              mountPath: /var/www/html/
        - image: mysql:8.0 # mysql container for keeping php data 
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
              memory: 256Mi
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: dbName
            - name: MYSQL_USER
              valueFrom:  
                secretKeyRef:
                  name: mysql-secret
                  key: dbUserNameKey
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: dbPasswordKey
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: rootPasswordKey
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts: # volume for mysql data
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        - name: nginx   # nginx web server for php app
          image: nginx:latest
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-files
# mount volume for communication between nginx and php
              mountPath: /var/www/html/
            - name: nginx-config-volume # mount volume for nginx config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: mysql-persistent-storage  # mysql storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: shared-files              
# volume for communication between nginx and php
          emptyDir: {}
        - name: nginx-config-volume       
# volume for nginx config from configmap
          configMap:
            name: nginx-config

