# ConfigMap for Nginx configuration

apiVersion: v1  # Kubernetes API version for ConfigMaps

kind: ConfigMap  # Kind of Kubernetes resource: ConfigMap

metadata:
  name: nginx-config  # ConfigMap name

  labels:
    app: laravel  # Label for identifying ConfigMap belonging to Laravel app

data:
  # Key-value pairs where the key is the filename and value is the content

  nginx.conf: |  # Key for Nginx configuration file
    # Nginx configuration content in YAML multi-line string format

    events {
    }

    http {
      server {
        listen 80 default_server;  # Listen on port 80 and set as default server
        listen [::]:80 default_server;  # Listen on IPv6 port 80 as well (optional)

        # Set root directory to the mounted volume for shared files
        root /var/www/html/vdc/public;

        server_name _;  # Match any hostname

        location / {  # Match all requests to the root path
          try_files $uri /index.php$is_args$args;  # Try to serve static files, otherwise fallback to index.php
        }

        location ~ \.php$ {  # Match all requests ending with .php
          try_files $uri /index.php$is_args$args;  # Try to serve static files, otherwise fallback to index.php

          include fastcgi_params;  # Include standard FastCGI parameters

          # Define FastCGI parameters for communication with Laravel application
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass localhost:9000;  # Pass requests to Laravel application on port 9000
        }
      }
    }
