apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel
spec:
  maxReplicas: 4
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 25
        type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel
