# Horizontal Pod Autoscaler (HPA) for the "laravel" deployment

apiVersion: autoscaling/v2  # Kubernetes API version for HPAs (v2)

kind: HorizontalPodAutoscaler  # Kind of Kubernetes resource: HPA

metadata:
  # Metadata for the HPA resource

  name: laravel  # HPA name (matches the deployment it scales)
  namespace: default  # Namespace where the HPA is deployed (default)
  # ... other metadata omitted for brevity (creationTimestamp, resourceVersion, uid)

spec:
  # HPA configuration

  maxReplicas: 4  # Maximum number of pods the HPA can scale the deployment to
  minReplicas: 1  # Minimum number of pods the HPA can scale the deployment down to

  metrics:
  - type: Resource  # Metric type: Resource utilization
    resource:  # Resource to track
      name: cpu  # CPU utilization for scaling
      target:  # Target utilization for scaling
        type: Utilization  # Target type: CPU usage percentage
        averageUtilization: 25  # Desired average CPU utilization (25%)

  scaleTargetRef:  # Reference to the deployment being scaled
    apiVersion: apps/v1  # API version of the deployment (v1)
    kind: Deployment  # Kind of resource: Deployment
    name: laravel  # Name of the deployment to scale ("laravel")

status:
  # Current status of the HPA

  currentReplicas: 1  # Number of replicas currently running in the deployment
  desiredReplicas: 1  # Number of replicas the HPA currently desires (based on metrics)
  lastScaleTime: "2024-04-07T05:26:39Z"  # Timestamp of the last scaling event

  conditions:  # List of conditions indicating HPA status
  - type: AbleToScale  # HPA is able to scale the deployment
    status: "True"  # Able to scale
    reason: ReadyForNewScale  # Ready to scale based on metrics
    lastTransitionTime: "2024-04-07T05:17:21Z"  # Last transition time

  - type: ScalingActive  # HPA has successfully calculated a replica count
    status: "True"  # Scaling is active
    reason: ValidMetricFound  # Valid metric (CPU utilization) found for scaling
    lastTransitionTime: "2024-04-07T05:17:21Z"  # Last transition time

  - type: ScalingLimited  # Desired replica count is within acceptable range
    status: "False"  # Currently limited (desired count within range)
    reason: DesiredWithinRange  # Desired replicas within min and max limits
    lastTransitionTime: "2024-04-07T05:17:21Z"  # Last transition time

  currentMetrics:  # Current metrics reported to the HPA
  - type: Resource  # Metric type: Resource utilization
    name: cpu  # CPU utilization metric
    current:  # Current CPU utilization data
      averageUtilization: 1  # Average CPU utilization (1%)
      averageValue: 6m  # Averaging window for CPU utilization (6 minutes)
