# Ingress resource for "laravel" service

apiVersion: networking.k8s.io/v1  # Kubernetes API version for Ingresses (v1)

kind: Ingress  # Kind of Kubernetes resource: Ingress

metadata:
  # Metadata for the Ingress resource

  name: learn-dep-k8s-ingress  # Name of the Ingress resource

  annotations:  # Optional annotations for the Ingress

    # Rewrite all requests to the root path (/)
    ingress.kubernetes.io/rewrite-target: /

spec:
  # Ingress specification

  rules:
  - # A rule for routing traffic

    host: laravel.ltv.lv  # Hostname for which this rule applies

    http:  # Configure HTTP paths within this rule

      paths:
      - # A path definition for routing

        path: /  # Matches requests to any path under "/"
        pathType: Prefix  # Match requests starting with "/"

        backend:  # Backend configuration for routing requests

          service:  # Service to route traffic to
            name: laravel  # Name of the service (matches deployment name)
            port:  # Port on which the service listens
              number: 80  # Service port number (usually 80 for HTTP)
