apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local  # Optional label for identification
spec:
  storageClassName: standard  # Lowercase for standard storage class
  capacity:
    storage: 50Mi  # Use Mi (mebibytes) for better representation
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Keep host path (for development/testing)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard  # Lowercase for standard storage class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi  # Use Mi (mebibytes) for better representation

