# Persistent Volume (PV) for MySQL data

apiVersion: v1  # Kubernetes API version for Persistent Volumes (v1)

kind: PersistentVolume  # Kind of Kubernetes resource: Persistent Volume

metadata:
  # Metadata for the Persistent Volume resource

  name: mysql-pv-volume  # Name of the Persistent Volume

  labels:  # Optional labels for identifying the PV

    type: local  # Label indicating local storage provisioner

spec:
  # Persistent Volume specification

  storageClassName: standart  # Storage class associated with the PV (can be customized)

  capacity:  # Capacity of the storage provisioned
    storage: 50M  # Size of the PV (50 Megabytes)

  accessModes:  # Access modes allowed for the PV
  - ReadWriteOnce  # Pod can have read-write access, single writer

  hostPath:  # Configuration for local storage provisioner
    path: "/mnt/data"  # Path on the host machine where data is stored

---

# Persistent Volume Claim (PVC) for MySQL deployment

apiVersion: v1  # Kubernetes API version for Persistent Volume Claims (v1)

kind: PersistentVolumeClaim  # Kind of Kubernetes resource: Persistent Volume Claim

metadata:
  # Metadata for the Persistent Volume Claim resource

  name: mysql-pv-claim  # Name of the Persistent Volume Claim

spec:
  # Persistent Volume Claim specification

  storageClassName: standart  # Storage class requested by the PVC (matches PV)

  accessModes:  # Access modes requested by the PVC
  - ReadWriteOnce  # Pod needs read-write access, single writer

  resources:
    requests:  # Requested storage resources
      storage: 50M  # Requested size of the PVC (50 Megabytes)
