# Service definition for the Laravel application

apiVersion: v1  # Kubernetes API version for Services (v1)

kind: Service  # Kind of Kubernetes resource: Service

metadata:
  # Metadata for the Service resource

  name: laravel  # Name of the Service (matches deployment name)

  labels:  # Labels for identifying Pods belonging to this Service
    app: laravel  # Label to select Pods with "app: laravel"

spec:
  # Service specification

  type: NodePort  # Service type: Expose service externally through NodePorts

  ports:  # Service ports

  - nodePort: 32223  # NodePort for external access (can be any unused port)
    port: 80  # Container port of the Laravel application
    name: php-8000  # Optional name for the port (descriptive)

  - port: 9000  # Internal port for communication within the cluster
    name: php-9000  # Optional name for the port (descriptive)

  - port: 3306  # Port for the MySQL database
    name: mysql  # Optional name for the port (descriptive)

  selector:  # Pod selector for selecting Pods to expose

    app: laravel  # Select Pods with label "app: laravel"
